import 'dart:convert';

import 'package:dozen_diamond/AD_Orders/models/get_all_open_order_list_response.dart'
    as getAllOpenOrderListResponse;

import '../../global/constants/currency_constants.dart';

class OrderRestApiServiceDummyData {
  Future<getAllOpenOrderListResponse.GetAllOpenOrderListResponse?>
      getOpenOrdersDummyData(
          CurrencyConstants currencyConstantsProvider) async {
    String jsonString;

    if (currencyConstantsProvider.currency == "₹") {
      jsonString =
          '''{
                      "status": true,
                      "message": "Open orders fetched successfully",
                      "success": {
                        "description": "All open orders are fetched successfully",
                        "suggestion": "Check orders periodically"
                      },
                      "data": [
                        {
                          "opo_buy_id": 123,
                          "opo_buy_unit": 50,
                          "opo_buy_stock_name": "TCS",
                          "opo_buy_ladder_name": "Ladder 1",
                          "user_id": 456,
                          "opo_buy_entry": "4424.58",
                          "opo_cash_gain_after_order": "100.00",
                          "opo_buy_remaining_cash": "2000.00",
                          "opo_buy_step_size": "126.42",
                          "opo_buy_ticket_num": "TICKET789",
                          "opo_def_buy_qty": 4,
                          "is_replicated_opo": false,
                          "is_deleted": 0,
                          "lad_id": 789,
                          "order_id": null,
                          "status": "pending",
                          "security_code": "SEC123",
                          "createdAt": "2024-09-13T12:34:56.789Z",
                          "updatedAt": "2024-09-14T13:45:23.123Z",
                          "order_type": "BUY",
                          "time": 1694706896789,
                          "current_price": "510.00",
                          "opo_sell_id": 321,
                          "opo_sell_unit": 20,
                          "opo_sell_stock_name": "TCS",
                          "opo_sell_lad_name": "Ladder 2",
                          "opo_sell_entry": "400.00",
                          "opo_sell_remaining_cash": "4677.42",
                          "opo_sell_step_size": "1",
                          "opo_sell_ticket_num": "TICKET123",
                          "opo_def_sell_qty": 3
                        },
                        {
                          "opo_buy_id": 123,
                          "opo_buy_unit": 50,
                          "opo_buy_stock_name": "TCS",
                          "opo_buy_ladder_name": "Ladder 1",
                          "user_id": 456,
                          "opo_buy_entry": "500.00",
                          "opo_cash_gain_after_order": "100.00",
                          "opo_buy_remaining_cash": "2000.00",
                          "opo_buy_step_size": "126.42",
                          "opo_buy_ticket_num": "TICKET789",
                          "opo_def_buy_qty": 5,
                          "is_replicated_opo": false,
                          "is_deleted": 0,
                          "lad_id": 789,
                          "order_id": null,
                          "status": "pending",
                          "security_code": "SEC123",
                          "createdAt": "2024-09-13T12:34:56.789Z",
                          "updatedAt": "2024-09-14T13:45:23.123Z",
                          "order_type": "SELL",
                          "time": 1694706896789,
                          "current_price": "510.00",
                         "opo_sell_id": 321,
                          "opo_sell_unit": 20,
                          "opo_sell_stock_name": "TCS",
                          "opo_sell_lad_name": "Ladder 2",
                          "opo_sell_entry": "400.00",
                          "opo_sell_remaining_cash": "4677.42",
                          "opo_sell_step_size": "1",
                          "opo_sell_ticket_num": "TICKET123",
                          "opo_def_sell_qty": 3   
                        }
                       
                      ]
                    }
                ''';
    } else {
      jsonString =
          '''{
                      "status": true,
                      "message": "Open orders fetched successfully",
                      "success": {
                        "description": "All open orders are fetched successfully",
                        "suggestion": "Check orders periodically"
                      },
                      "data": [
                        {
                          "opo_buy_id": 123,
                          "opo_buy_unit": 13,
                          "opo_buy_stock_name": "Microsoft Corp",
                          "opo_buy_ladder_name": "Ladder 001",
                          "user_id": 456,
                          "opo_buy_entry": "397.47",
                          "opo_cash_gain_after_order": "100.00",
                          "opo_buy_remaining_cash": "2000.00",
                          "opo_buy_step_size": "1",
                          "opo_buy_ticket_num": "TICKET789",
                          "opo_def_buy_qty": 5,
                          "is_replicated_opo": false,
                          "is_deleted": 0,
                          "lad_id": 789,
                          "order_id": null,
                          "status": "pending",
                          "security_code": "SEC123",
                          "createdAt": "2024-09-13T12:34:56.789Z",
                          "updatedAt": "2024-09-14T13:45:23.123Z",
                          "order_type": "BUY",
                          "time": 1694706896789,
                          "current_price": "408.51",
                          "opo_sell_id": 321,
                          "opo_sell_unit": 20,
                          "opo_sell_stock_name": "XYZ Ltd",
                          "opo_sell_lad_name": "Ladder 2",
                          "opo_sell_entry": "400.00",
                          "opo_sell_remaining_cash": "1500.00",
                          "opo_sell_step_size": "1",
                          "opo_sell_ticket_num": "TICKET123",
                          "opo_def_sell_qty": 3
                        },
                        {
                          "opo_buy_id": 123,
                          "opo_buy_unit": 50,
                          "opo_buy_stock_name": "Microsoft Corp",
                          "opo_buy_ladder_name": "Ladder 001",
                          "user_id": 456,
                          "opo_buy_entry": "500.00",
                          "opo_cash_gain_after_order": "100.00",
                          "opo_buy_remaining_cash": "2000.00",
                          "opo_buy_step_size": "1",
                          "opo_buy_ticket_num": "TICKET789",
                          "opo_def_buy_qty": 5,
                          "is_replicated_opo": false,
                          "is_deleted": 0,
                          "lad_id": 789,
                          "order_id": null,
                          "status": "pending",
                          "security_code": "SEC123",
                          "createdAt": "2024-09-13T12:34:56.789Z",
                          "updatedAt": "2024-09-14T13:45:23.123Z",
                          "order_type": "BUY",
                          "time": 1694706896789,
                          "current_price": "408.51",
                          "opo_sell_id": 321,
                          "opo_sell_unit": 20,
                          "opo_sell_stock_name": "Microsoft Corp",
                          "opo_sell_lad_name": "Ladder 2",
                          "opo_sell_entry": "400.00",
                          "opo_sell_remaining_cash": "1500.00",
                          "opo_sell_step_size": "1",
                          "opo_sell_ticket_num": "TICKET123",
                          "opo_def_sell_qty": 3
                        },
                        {
                          "opo_buy_id": 123,
                          "opo_buy_unit": 50,
                          "opo_buy_stock_name": "Amazon.com Inc",
                          "opo_buy_ladder_name": "Ladder 1",
                          "user_id": 456,
                          "opo_buy_entry": "500.00",
                          "opo_cash_gain_after_order": "100.00",
                          "opo_buy_remaining_cash": "2000.00",
                          "opo_buy_step_size": "1",
                          "opo_buy_ticket_num": "TICKET789",
                          "opo_def_buy_qty": 5,
                          "is_replicated_opo": false,
                          "is_deleted": 0,
                          "lad_id": 789,
                          "order_id": null,
                          "status": "pending",
                          "security_code": "SEC123",
                          "createdAt": "2024-09-13T12:34:56.789Z",
                          "updatedAt": "2024-09-14T13:45:23.123Z",
                          "order_type": "BUY",
                          "time": 1694706896789,
                          "current_price": "189.90",
                          "opo_sell_id": 321,
                          "opo_sell_unit": 20,
                          "opo_sell_stock_name": "Amazon.com Inc",
                          "opo_sell_lad_name": "Ladder 2",
                          "opo_sell_entry": "400.00",
                          "opo_sell_remaining_cash": "1500.00",
                          "opo_sell_step_size": "1",
                          "opo_sell_ticket_num": "TICKET123",
                          "opo_def_sell_qty": 3
                        },
                        {
                          "opo_buy_id": 124,
                          "opo_buy_unit": 75,
                          "opo_buy_stock_name": "Amazon.com Inc",
                          "opo_buy_ladder_name": "Ladder 3",
                          "user_id": 457,
                          "opo_buy_entry": "700.00",
                          "opo_cash_gain_after_order": "150.00",
                          "opo_buy_remaining_cash": "3500.00",
                          "opo_buy_step_size": "2",
                          "opo_buy_ticket_num": "TICKET456",
                          "opo_def_buy_qty": 10,
                          "is_replicated_opo": true,
                          "is_deleted": 1,
                          "lad_id": 790,
                          "order_id": null,
                          "status": "completed",
                          "security_code": "SEC456",
                          "createdAt": "2024-09-12T10:22:33.456Z",
                          "updatedAt": "2024-09-13T11:55:12.789Z",
                          "order_type": "SELL",
                          "time": 1694701234567,
                          "current_price": "189.90",
                          "opo_sell_id": 322,
                          "opo_sell_unit": 35,
                          "opo_sell_stock_name": "Amazon.com Inc",
                          "opo_sell_lad_name": "Ladder 4",
                          "opo_sell_entry": "650.00",
                          "opo_sell_remaining_cash": "3000.00",
                          "opo_sell_step_size": "2",
                          "opo_sell_ticket_num": "TICKET789",
                          "opo_def_sell_qty": 7
                        },
                        {
                          "opo_buy_id": 124,
                          "opo_buy_unit": 75,
                          "opo_buy_stock_name": "Alphabet Inc",
                          "opo_buy_ladder_name": "Ladder 3",
                          "user_id": 457,
                          "opo_buy_entry": "700.00",
                          "opo_cash_gain_after_order": "150.00",
                          "opo_buy_remaining_cash": "3500.00",
                          "opo_buy_step_size": "2",
                          "opo_buy_ticket_num": "TICKET456",
                          "opo_def_buy_qty": 10,
                          "is_replicated_opo": true,
                          "is_deleted": 1,
                          "lad_id": 790,
                          "order_id": null,
                          "status": "completed",
                          "security_code": "SEC456",
                          "createdAt": "2024-09-12T10:22:33.456Z",
                          "updatedAt": "2024-09-13T11:55:12.789Z",
                          "order_type": "SELL",
                          "time": 1694701234567,
                          "current_price": "163.67",
                          "opo_sell_id": 322,
                          "opo_sell_unit": 35,
                          "opo_sell_stock_name": "Alphabet Inc",
                          "opo_sell_lad_name": "Ladder 4",
                          "opo_sell_entry": "650.00",
                          "opo_sell_remaining_cash": "3000.00",
                          "opo_sell_step_size": "2",
                          "opo_sell_ticket_num": "TICKET789",
                          "opo_def_sell_qty": 7
                        },
                        {
                          "opo_buy_id": 124,
                          "opo_buy_unit": 75,
                          "opo_buy_stock_name": "Alphabet Inc",
                          "opo_buy_ladder_name": "Ladder 3",
                          "user_id": 457,
                          "opo_buy_entry": "700.00",
                          "opo_cash_gain_after_order": "150.00",
                          "opo_buy_remaining_cash": "3500.00",
                          "opo_buy_step_size": "2",
                          "opo_buy_ticket_num": "TICKET456",
                          "opo_def_buy_qty": 10,
                          "is_replicated_opo": true,
                          "is_deleted": 1,
                          "lad_id": 790,
                          "order_id": null,
                          "status": "completed",
                          "security_code": "SEC456",
                          "createdAt": "2024-09-12T10:22:33.456Z",
                          "updatedAt": "2024-09-13T11:55:12.789Z",
                          "order_type": "SELL",
                          "time": 1694701234567,
                          "current_price": "163.67",
                          "opo_sell_id": 322,
                          "opo_sell_unit": 35,
                          "opo_sell_stock_name": "Alphabet Inc",
                          "opo_sell_lad_name": "Ladder 4",
                          "opo_sell_entry": "650.00",
                          "opo_sell_remaining_cash": "3000.00",
                          "opo_sell_step_size": "2",
                          "opo_sell_ticket_num": "TICKET789",
                          "opo_def_sell_qty": 7
                        }
                      ]
                    }
                ''';
    }

    getAllOpenOrderListResponse.GetAllOpenOrderListResponse value =
        getAllOpenOrderListResponse.GetAllOpenOrderListResponse()
            .fromJson(jsonDecode(jsonString));
    print("value ${value.toJson()}");
    return value;
  }
}
